dagster._core.errors.DagsterUserCodeLoadError: Error occurred during the loading of Dagster definitions in
executable_path=C:\Users\Cikal Merdeka\AppData\Local\Programs\Python\Python311\python.exe, module_name=dbt_dagster_project.definitions, working_directory=E:\Udemy\dbt\The Complete dbt (Data Build Tool) Bootcamp Zero to Hero\course\dbt_dagster_project
  File "C:\Users\Cikal Merdeka\AppData\Local\Programs\Python\Python311\Lib\site-packages\dagster\_grpc\server.py", line 411, in __init__
    self._loaded_repositories: Optional[LoadedRepositories] = LoadedRepositories(
                                                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cikal Merdeka\AppData\Local\Programs\Python\Python311\Lib\site-packages\dagster\_grpc\server.py", line 234, in __init__
    with user_code_error_boundary(
  File "C:\Users\Cikal Merdeka\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Cikal Merdeka\AppData\Local\Programs\Python\Python311\Lib\site-packages\dagster\_core\errors.py", line 297, in user_code_error_boundary
    raise new_error from e
The above exception was caused by the following exception:
dagster_dbt.errors.DagsterDbtCliRuntimeError: The dbt CLI process with command

`dbt --quiet parse`

failed with exit code `1`. Check the stdout in the Dagster compute logs for the full information about the error.
  File "C:\Users\Cikal Merdeka\AppData\Local\Programs\Python\Python311\Lib\site-packages\dagster\_core\errors.py", line 287, in user_code_error_boundary
    yield
  File "C:\Users\Cikal Merdeka\AppData\Local\Programs\Python\Python311\Lib\site-packages\dagster\_grpc\server.py", line 245, in __init__
    loadable_targets = get_loadable_targets(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cikal Merdeka\AppData\Local\Programs\Python\Python311\Lib\site-packages\dagster\_grpc\utils.py", line 50, in get_loadable_targets
    else loadable_targets_from_python_module(module_name, working_directory)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cikal Merdeka\AppData\Local\Programs\Python\Python311\Lib\site-packages\dagster\_core\workspace\autodiscovery.py", line 31, in loadable_targets_from_python_module
    module = load_python_module(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cikal Merdeka\AppData\Local\Programs\Python\Python311\Lib\site-packages\dagster\_core\code_pointer.py", line 134, in load_python_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cikal Merdeka\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Udemy\dbt\The Complete dbt (Data Build Tool) Bootcamp Zero to Hero\course\dbt_dagster_project\dbt_dagster_project\definitions.py", line 6, in <module>
    from .assets import dbtlearn_dbt_assets
  File "E:\Udemy\dbt\The Complete dbt (Data Build Tool) Bootcamp Zero to Hero\course\dbt_dagster_project\dbt_dagster_project\assets.py", line 4, in <module>
    from .constants import dbt_manifest_path
  File "E:\Udemy\dbt\The Complete dbt (Data Build Tool) Bootcamp Zero to Hero\course\dbt_dagster_project\dbt_dagster_project\constants.py", line 17, in <module>
    .wait()
     ^^^^^^
  File "C:\Users\Cikal Merdeka\AppData\Local\Programs\Python\Python311\Lib\site-packages\dagster_dbt\core\resources_v2.py", line 549, in wait
    list(self.stream_raw_events())
  File "C:\Users\Cikal Merdeka\AppData\Local\Programs\Python\Python311\Lib\site-packages\dagster_dbt\core\resources_v2.py", line 712, in stream_raw_events
    self._raise_on_error()
  File "C:\Users\Cikal Merdeka\AppData\Local\Programs\Python\Python311\Lib\site-packages\dagster_dbt\core\resources_v2.py", line 804, in _raise_on_error
    raise error